server {
    listen       80;
    server_name  responsive.vm1.test responsive.vm2.test responsive.vm3.test responsive.vm4.test responsive.vm5.test responsive.vm6.test;



     location / {
        proxy_pass http://responsive:8080/;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;

        error_page 502 /502.html;
    }

    location = /502.html {
        internal;
        default_type text/html;
        charset utf-8;
        return 502 '<html><body><h1>Fut a Rszponzív?</h1></body></html>';
    }

}